//Traduções Compartilhadas
const TraducaoGeral = {
	'en': {
		'ataque':'Attack',
		'defesa':'Defense',	
		'hp':'Vitality',
		'efeitotexto':'Effect: ',		
		'nvminimo':'Required Level',
		'itemcomum':'Common',
		'itemraro':'Rare',
		'itemepico':'Epic',
		'itemlendario':'Relic',
		'itemsupremo':'Supreme',
		'menutitulomissao':'Crest',			
		'dropsaleatorios':'Random Drops',
		'itensconstruidos':'Crafted Items',
		'podemover':'Warehouse Move Allowed',
		'naopodemover':'Warehouse Move Not Allowed',
		'heroico':'Champion',
		'infernal':'Hell',
		'inicioguias':'Home',
		'wiki':'Wiki',		
		'atk':'Attack',
		'atkspc':'Special Attack',
		'danocritico':'Critical Damage',
		'resistenciacorrupcao':'Corruption Resistance',
        'pecasvazio': 'Set Item: Void Devourer<br/>3 Pieces Bonus:',
        'pecashenir': 'Set Item: Otherworld Lord<br/>3 Pieces Bonus:',
		'detalhesmissao':'Mission Details'
	},
	'pt': {
		'ataque':'Ataque',
		'defesa':'Defesa',
		'hp':'HP',
		'efeitotexto':'Efeito: ',		
		'nvminimo':'Nv minimo',
		'itemcomum':'Item Comum',
		'itemraro':'Item Raro',
		'itemepico':'Item Épico',
		'itemlendario':'Item Lendário',
		'itemsupremo':'Item Supremo',
		'menutitulomissao':'Título',			
		'dropsaleatorios':'Drops Aleatórios',		
		'itensconstruidos':'Itens Construídos',
		'podemover':'Pode ser movido para o Armazém',
		'naopodemover':'Não pode ser movido para o Armazém',
		'heroico':'Heróico',
		'infernal':'Infernal',		
		'drops':'Drops',
		'normal':'Normal',
		'inicioguias':'Início',		
		'atk':'Ataque',
		'atkspc':'Ataque Especial',
		'danocritico':'Dano Crítico',
		'resistenciacorrupcao':'Resistência a Corrupção',
        'pecasvazio': 'Atributos do Conjunto: Devorador do Vazio<br/>3 Peças Bônus:',
        'pecashenir': 'Atributos do Conjunto: Senhor de Outro Mundo<br/>3 Peças Bônus:',
		'detalhesmissao':'Detalhes da Missão'		
	},
	'es': {
		'ataque':'Ataque',
		'defesa':'Defensa',
		'hp':'Vitalidad',
		'efeitotexto':'Efecto: ',
		'dropaleatorio':'Aleatorio',
		'nvminimo':'Nivel Requerido',
		'itemcomum':'Común',
		'itemraro':'Raro',
		'itemepico':'Épico',
		'itemlendario':'Reliquia',
		'itemsupremo':'Supremo',
		'menutitulomissao':'Título',			
		'dropsaleatorios':'Drops Aleatorios',
		'itensconstruidos':'Ítems Construidos',
		'podemover':'Permitir Mover al Almacén',
		'naopodemover':'No Permitir Mover al Almacén',
		'heroico':'Campeón',
		'infernal':'Infierno',
		'inicioguias':'Inicio',
		'atk': 'Ataque',
		'atkspc': 'Ataque Especial',
		'danocritico': 'Daño Crítico',
		'resistenciacorrupcao': 'Resistencia a la Corrupción',
        'pecasvazio': 'Atributos del Conjunto: Devorador del Vacío<br/>3 Piezas Bono:',
        'pecashenir': 'Atributos del Conjunto: Señor de Otro Mundo<br/>3 Piezas Bono:',		
		'detalhesmissao':'Detalles de la Misión'
	},
	'ph': {
		'ataque':'Atake',
		'defesa':'Depensa',
		'hp':'Buhay',
		'efeitotexto':'Epekto: ',		
		'nvminimo':'Kinakailangan Antas',
		'itemcomum':'Karaniwan',
		'itemraro':'Bihira',
		'itemepico':'Epiko',
		'itemlendario':'Relikya',
		'itemsupremo':'Supremo',
		'menutitulomissao':'Titulo',
		'dropsaleatorios':'Pabagu-bagong Drops',
		'itensconstruidos':'Ginawang mga Bagay',
		'podemover':'Pinapayagan Maglipat ng Bodega',
		'naopodemover':'Hindi Pinapayagan Maglipat ng Bodega',
		'heroico':'Kampyon',
		'infernal':'Impiyerno',		
		'atk': 'Atake',
		'inicioguias':'Simula',
		'atkspc': 'Espesyal na Atake',
		'danocritico': 'Kritikal na Pinsala',
		'resistenciacorrupcao': 'Paglaban sa Katiwalian',
        'pecasvazio': 'Mga Katangian ng Set: Mangangain ng Void<br/>Bonus para sa 3 Piraso:',
        'pecashenir': 'Mga Katangian ng Set: Panginoon ng Ibang Mundo<br/>Bonus para sa 3 Piraso:',
		'detalhesmissao':'Detalye ng Misyon'
	},
	'cn': {
		'ataque':'攻擊力',
        'defesa':'防禦力',
        'hp':'生命力',
        'efeitotexto':'效果: ',
        'nvminimo':'要求等級',
        'itemcomum':'普通物品',
        'itemraro':'稀有物品',
        'itemepico':'史詩物品',
        'itemlendario':'傳說物品',
        'itemsupremo':'尊爵不凡',
        'menutitulomissao':'頭銜',
        'dropsaleatorios':'隨機掉落',
        'itensconstruidos':'製作物品',
        'podemover':'允許移動至倉庫',
        'naopodemover':'不允許移動至倉庫',
        'heroico':'冠軍',
        'infernal':'地獄',        
		'inicioguias':'目录',
        'drops':'固定掉落',
        'normal':'普通',
		'atk': '攻击',
		'atkspc': '特殊攻击',
		'danocritico': '暴击伤害',
		'resistenciacorrupcao': '腐化抵抗',
        'pecasvazio': '套装属性：虚空吞噬者<br/>3件套奖励：',
        'pecashenir': '套装属性：异世界之主<br/>3件套奖励：',
        'detalhesmissao':'關卡細節'
	},
	'id': {
		'ataque':'Attack',
		'defesa':'Defense',
		'hp':'Vitality',
		'efeitotexto':'Efek: ',
		'nvminimo':'Level yang Dibutuhkan',
		'itemcomum':'Common',
		'itemraro':'Rare',
		'itemepico':'Epic',
		'itemlendario':'Relic',
		'itemsupremo':'Supreme',
		'menutitulomissao':'Title',
		'dropsaleatorios':'Drops Acak',
		'itensconstruidos':'Crafted Items',
		'podemover':'Dapat Dipindahkan ke Gudang',
		'naopodemover':'Tidak Dapat Dipindahkan ke Gudang',
		'heroico':'Champion',
		'infernal':'Infernal',		
		'inicioguias':'Utama',
		'detalhesmissao':'Detail Misi'
	},
	'th': {	
		'ataque':'พลังโจมตี',
		'defesa':'ป้องกัน',
		'hp':'ชีวิต',
		'efeitotexto':'ผล: ',		
		'nvminimo':'เลเวลที่ต้องการ',
		'itemcomum':'ทั่วไป',
		'itemraro':'หายาก',
		'itemepico':'มหากาพย์',
		'itemlendario':'ของโบราณ',
		'itemsupremo':'สูงสุด',
		'menutitulomissao':'ตรา',
		'dropsaleatorios':'ดรอปสุ่ม',
		'itensconstruidos':'ไอเทมที่สร้างขึ้น',
		'podemover':'อนุญาตให้ย้ายไปยังคลังสินค้า',
		'naopodemover':'ไม่อนุญาตให้ย้ายไปยังคลังสินค้า',
		'heroico':'แชมป์เปี้ยน',
		'infernal':'นรก',
		'wiki':'วิกิ',
		'inicioguias':'หน้าหลัก',
		'drops':'ดรอป',
		'normal':'ปกติ',
		'atk': 'พลังโจมตี',
		'atkspc': 'การโจมตีพิเศษ',
		'danocritico': 'ความเสียหายรุนแรง',
		'resistenciacorrupcao': 'ความต้านทานการคอร์รัปชั่น',
        'pecasvazio': 'คุณสมบัติชุด: ผู้กลืนกินแห่งความว่างเปล่า<br/>โบนัส 3 ชิ้น:',
        'pecashenir': 'คุณสมบัติชุด: เจ้าแห่งอีกโลกหนึ่ง<br/>โบนัส 3 ชิ้น:',
		'detalhesmissao':'รายละเอียดภารกิจ'
	}
};
addTranslations(TraducaoGeral);

//TRADUÇÕES DE MISSÕES
const TraducaoBerco = {
	'en': {		
		'titulomissao':'',
		'title': 'Cradle of Scarlet Flames',
		'detalhenormal':'Each stage has a crystal that needs to be destroyed in order to damage monsters.',
		'detalheheroico':'In the boss stage, you will need to defeat all the naga to be able to damage the boss.',
		'titulomissao':'The Fall of Fury',
		'item1793440_nomedoitem':'The Fall of Fury',
		'item1793440_tipo':'Title',
		'item1793440_custo':'Crystal 0',		
		'item1793440_efeito1':'Critical Damage +18.00%',		
		'item1793440_efeito2':'Spawn Invincibility +20.00%',	
		'item1793440_efeito3':'Special Resistance + 16.00%'
	},
	'pt': {		
		'titulomissao':'A Queda da Fúria',
		'title': 'Berço das Chamas Escarlates',
		'detalhenormal':'Cada estágio possui um cristal que precisa ser destruído para poder causar dano aos monstros.',
		'detalheheroico':'No estágio do chefe, será necessário derrotar as nagas para poder conseguir dar dano no chefe.',
		'item1793440_nomedoitem':'A Queda da Fúria',
		'item1793440_tipo':'Título',
		'item1793440_custo':'Cristal 0',
		'item1793440_efeito1':'Dano Crítico +18.00%',		
		'item1793440_efeito2':'Tempo de invencibilidade na arena +20.00%',	
		'item1793440_efeito3':'Resistência a status anormais + 16.00%'				
	},
	'es': {
		'titulomissao':'La Caída de la Furia',
		'title': 'Cuna de Llamas Escarlatas',
		'detalhenormal':'Cada etapa tiene un cristal que necesita ser destruido para dañar a los monstruos.',
		'detalheheroico':'En la etapa del jefe, necesitarás derrotar a todas las nagas para poder dañar al jefe.',
		'item1793440_nomedoitem':'La Caída de la Furia',
		'item1793440_tipo':'Título',
		'item1793440_custo':'Cristal 0',
		'item1793440_efeito1':'Daño Crítico +18.00%',		
		'item1793440_efeito2':'Invencibilidad de Aparición +20.00%',	
		'item1793440_efeito3':'Resistencia Especial + 16.00%'	
	},
	'cn': {
		'titulomissao':'愤怒的堕落',
		'title': '红炎的摇篮',
		'detalhenormal':'每个阶段都有一个水晶，需要摧毁它才能对怪物造成伤害。',
		'detalheheroico':'在boss阶段，你需要击败所有的娜迦才能对boss造成伤害。',
		'item1793440_nomedoitem':'愤怒的堕落',
		'item1793440_tipo':'称号',
		'item1793440_custo':'水晶 0',
		'item1793440_efeito1':'暴击伤害 +18.00%',		
		'item1793440_efeito2':'出生无敌 +20.00%',	
		'item1793440_efeito3':'特殊抗性 + 16.00%'
	},
	'ph': {
		'titulomissao':'Ang Pagbagsak ng Galit',
		'title': 'Duyan ng mga Pulang Apoy',
		'detalhenormal':'Ang bawat yugto ay may kristal na kailangang sirain upang masaktan ang mga halimaw.',
		'detalheheroico':'Sa yugto ng boss, kakailanganin mong talunin ang lahat ng naga upang masaktan ang boss.',
		'item1793440_nomedoitem':'Ang Pagbagsak ng Galit',
		'item1793440_tipo':'Titulo',
		'item1793440_custo':'Kristal 0',
		'item1793440_efeito1':'Kritikal na Pinsala +18.00%',
		'item1793440_efeito2':'Invincibility Pag Spawn +20.00%',
		'item1793440_efeito3':'Special na Resistensya + 16.00%'
	},
	'id': {
		'titulomissao':'Keajaiban yang Jatuh',		
		'detalhenormal':'Setiap tahap memiliki kristal yang harus dihancurkan untuk merusak monster.',
		'detalheheroico':'Di tahap boss, kamu perlu mengalahkan semua naga untuk dapat merusak boss.',
		'item1793440_nomedoitem':'Keajaiban yang Jatuh',
		'item1793440_tipo':'Title',
		'item1793440_custo':'Kristal 0'		
	},
	'th': {
		'titulomissao':'ความโกรธเกรี้ยวที่ตกลงมา',
		'title': 'แหล่งเพลิงสีแดงเข้ม',
		'detalhenormal':'แต่ละด่านจะมีคริสตัลที่ต้องทำลายเพื่อทำให้สัตว์ประหลาดได้รับความเสียหาย',
		'detalheheroico':'ในด่านบอส คุณจะต้องเอาชนะนากาทั้งหมดเพื่อทำให้บอสได้รับความเสียหาย',
		'item1793440_nomedoitem':'ความโกรธเกรี้ยวที่ตกลงมา',
		'item1793440_tipo':'ชื่อเรื่อง',
		'item1793440_custo':'คริสตัล 0',
		'item1793440_efeito1':'ความเสียหายคริติคอล +18.00%',		
		'item1793440_efeito2':'ความคุ้มครองเกิดใหม่ +20.00%',	
		'item1793440_efeito3':'ความต้านทานพิเศษ + 16.00%'
	}
};

const TraducaoCripta = {
	'en': {
		'titulomissao':'Ancestral Sovereign',
		'title': 'Ancestral Crypt',
		'detalhenormal': 'Some stages need to be completed before the time runs out. If the time runs out, it will be necessary to complete 2 additional stages.',
		'detalheheroico': 'In champion mode, the mission becomes slightly more difficult, requiring you to defeat Vertus at the end.',
		'item2103820_nomedoitem':'Ancestral Sovereign',		
		'item2103820_tipo':'Title',
		'item2103820_custo':'Crystal 0',		
		'item2103820_efeito1':'Special Attack +400',
		'item2103820_efeito2':'Special Defense +400',
		'item2103820_efeito3':'Critical Damage +37.50%',		
		'item2103820_efeito4':'Hell Spear +400'
	},
	'pt': {		
		'titulomissao':'Soberano Ancestral',
		'title': 'Cripta Ancestral',
		'detalhenormal':'Alguns estágios precisam ser feitos antes do tempo acabar. Se o tempo acabar será necessário finalizar mais 2 estágios extras.',
		'detalheheroico':'No modo heróico a missão fica um pouco mais dificil sendo necessario derrotar o Vertus no final.',
		'item2103820_nomedoitem':'Soberano Ancestral',
		'item2103820_tipo':'Título',
		'item2103820_custo':'Cristal 0',		
		'item2103820_efeito1':'Ataque Especial +400',
		'item2103820_efeito2':'Defesa Especial +400',
		'item2103820_efeito3':'Dano Crítico +37.50%',
		'item2103820_efeito4':'Lança Infernal +400'
	},
	'cn': {		
		'titulomissao':'祖先的主宰',
		'title': '祖先地下室',
		'detalhenormal':'某些阶段需要在时间结束前完成。如果时间用完，将需要完成另外2个阶段。',
		'detalheheroico':'在英雄模式中，任务变得稍微困难一些，需要在最后打败Vertus。',
		'item2103820_nomedoitem':'祖先的主宰',
		'item2103820_tipo':'头衔',
		'item2103820_custo':'水晶 0',		
		'item2103820_efeito1':'特殊攻击 +400',
		'item2103820_efeito2':'特殊防御 +400',
		'item2103820_efeito3':'暴击伤害 +37.50%',
		'item2103820_efeito4':'地狱矛 +400'
	},
	'ph': {		
		'titulomissao':'Kataas-taasang Nuno',
		'title': 'Sinaunang Libingan',
		'detalhenormal':'Ang ilang mga yugto ay kailangang makumpleto bago maubos ang oras. Kung maubos ang oras, kakailanganing kumpletuhin ang karagdagang 2 yugto.',
		'detalheheroico':'Sa champion mode, ang misyon ay nagiging medyo mas mahirap, na nangangailangan ng talunin si Vertus sa huli.',
		'item2103820_nomedoitem':'Kataas-taasang Nuno',
		'item2103820_tipo':'Titulo',
		'item2103820_custo':'Kristal 0',		
		'item2103820_efeito1':'Espesyal na Atake +400',
		'item2103820_efeito2':'Espesyal na Depensa +400',
		'item2103820_efeito3':'Kritikal na Pinsala +37.50%',
		'item2103820_efeito4':'Impiyernong Sibat +400'
	},
	'th': {		
		'titulomissao':'ผู้ปกครองบรรพบุรุษ',
		'title': 'สุสานบรรพบุรุษ',
		'detalhenormal':'บางขั้นตอนจำเป็นต้องทำให้เสร็จก่อนที่เวลาจะหมดลง หากเวลาหมดลง จะต้องทำเพิ่มอีก 2 ขั้นตอน',
		'detalheheroico':'ในโหมดแชมเปี้ยน ภารกิจจะยากขึ้นเล็กน้อย ต้องเอาชนะ Vertus ในตอนท้าย',
		'item2103820_nomedoitem':'ผู้ปกครองบรรพบุรุษ',
		'item2103820_tipo':'ตำแหน่ง',
		'item2103820_custo':'คริสตัล 0',		
		'item2103820_efeito1':'การโจมตีพิเศษ +400',
		'item2103820_efeito2':'การป้องกันพิเศษ +400',
		'item2103820_efeito3':'ความเสียหายคริติคอล +37.50%',
		'item2103820_efeito4':'หอกนรก +400'
	},
	'id': {		
		'titulomissao':'Penguasa Leluhur',		
		'detalhenormal':'Beberapa tahap perlu diselesaikan sebelum waktu habis. Jika waktu habis, perlu menyelesaikan 2 tahap tambahan.',
		'detalheheroico':'Dalam mode juara, misinya menjadi sedikit lebih sulit, mengharuskan Anda mengalahkan Vertus di akhir.',
		'item2103820_nomedoitem':'Penguasa Leluhur',
		'item2103820_tipo':'Gelar',
		'item2103820_custo':'Kristal 0'
	},
	'es': {		
		'titulomissao':'Soberano Ancestral',
		'title': 'Cripta Ancestral',
		'detalhenormal':'Algunas etapas deben completarse antes de que se acabe el tiempo. Si el tiempo se acaba, será necesario completar 2 etapas adicionales.',
		'detalheheroico':'En el modo campeón, la misión se vuelve un poco más difícil, requiriendo derrotar a Vertus al final.',
		'item2103820_nomedoitem':'Soberano Ancestral',
		'item2103820_tipo':'Título',
		'item2103820_custo':'Cristal 0',		
		'item2103820_efeito1':'Ataque Especial +400',
		'item2103820_efeito2':'Defensa Especial +400',
		'item2103820_efeito3':'Daño Crítico +37.50%',
		'item2103820_efeito4':'Lanza Infernal +400'
	}
};

const TraducaoSantuario = {
	'en': {
		'titulomissao':'Sanctuary Conqueror',
		'title': 'Frozen Sanctuary',
		'detalhenormal': 'There is a stage where you need to defeat all the monsters in order to destroy the floor and continue.',
		'detalheheroico': 'In champion mode, the mission becomes slightly more difficult, requiring you to defeat Arleoth at the end.',
		'item2103840_nomedoitem':'Sanctuary Conqueror',		
		'item2103840_tipo':'Title',
		'item2103840_custo':'Crystal 0',		
		'item2103840_efeito1':'Special Attack +600',
		'item2103840_efeito2':'Special Defense +600',
		'item2103840_efeito3':'Critical Damage +48.60%',
		'item2103840_efeito4':'Hell Spear +600'
	},
	'pt': {		
		'titulomissao':'Conquistador do Santuário',
		'title': 'Santuário Esquecido',
		'detalhenormal':'Há um estágio em que você deve derrotar todos os monstros antes de poder destruir o chão e prosseguir.',
		'detalheheroico':'No modo heróico a missão fica um pouco mais difícil sendo necessário derrotar o Arleoth no final.',
		'item2103840_nomedoitem':'Conquistador do Santuário',
		'item2103840_tipo':'Título',
		'item2103840_custo':'Cristal 0',		
		'item2103840_efeito1':'Ataque Especial +600',
		'item2103840_efeito2':'Defesa Especial +600',
		'item2103840_efeito3':'Dano Crítico +48.60%',		
		'item2103840_efeito4':'Lança Infernal +600'
	},
	'cn': {		
		'titulomissao':'圣域征服者',
		'title': '冰冻圣域',
		'detalhenormal':'有一个阶段你需要击败所有怪物才能摧毁地板并继续前进。',
		'detalheheroico':'在冠军模式下，任务变得稍微困难一些，需要在最后击败Arleoth。',
		'item2103840_nomedoitem':'圣域征服者',
		'item2103840_tipo':'头衔',
		'item2103840_custo':'水晶 0',		
		'item2103840_efeito1':'特殊攻击 +600',
		'item2103840_efeito2':'特殊防御 +600',
		'item2103840_efeito3':'暴击伤害 +48.60%',
		'item2103840_efeito4':'地狱矛 +600'
	},
	'ph': {		
		'titulomissao':'Mananakop ng Santuwaryo',
		'title': 'Nagyeyelong Santuwaryo',
		'detalhenormal':'May isang yugto kung saan kailangan mong talunin ang lahat ng mga halimaw upang sirain ang sahig at magpatuloy.',
		'detalheheroico':'Sa mode na champion, ang misyon ay nagiging medyo mas mahirap, na nangangailangan ng talunin si Arleoth sa dulo.',
		'item2103840_nomedoitem':'Mananakop ng Santuwaryo',
		'item2103840_tipo':'Titulo',
		'item2103840_custo':'Kristal 0',		
		'item2103840_efeito1':'Espesyal na Atake +600',
		'item2103840_efeito2':'Espesyal na Depensa +600',
		'item2103840_efeito3':'Kritikal na Pinsala +48.60%',
		'item2103840_efeito4':'Impiyernong Sibat +600'
	},
	'th': {		
		'titulomissao':'ผู้พิชิตสถานที่ศักดิ์สิทธิ์',
		'title': 'สถานที่ศักดิ์สิทธิ์เยือกแข็ง',
		'detalhenormal':'มีด่านหนึ่งที่คุณต้องเอาชนะมอนสเตอร์ทั้งหมดเพื่อทำลายพื้นและดำเนินการต่อไป',
		'detalheheroico':'ในโหมดแชมเปี้ยน ภารกิจจะยากขึ้นเล็กน้อย ต้องเอาชนะ Arleoth ในตอนท้าย',
		'item2103840_nomedoitem':'ผู้พิชิตสถานที่ศักดิ์สิทธิ์',
		'item2103840_tipo':'ตำแหน่ง',
		'item2103840_custo':'คริสตัล 0',		
		'item2103840_efeito1':'การโจมตีพิเศษ +600',
		'item2103840_efeito2':'การป้องกันพิเศษ +600',
		'item2103840_efeito3':'ความเสียหายคริติคอล +48.60%',
		'item2103840_efeito4':'หอกนรก +600'
	},
	'id': {		
		'titulomissao':'Penakluk Tempat Suci',		
		'detalhenormal':'Ada tahap di mana Anda perlu mengalahkan semua monster untuk menghancurkan lantai dan melanjutkan.',
		'detalheheroico':'Dalam mode juara, misinya menjadi sedikit lebih sulit, mengharuskan Anda mengalahkan Arleoth di akhir.',
		'item2103840_nomedoitem':'Penakluk Tempat Suci',
		'item2103840_tipo':'Gelar',
		'item2103840_custo':'Kristal 0'
	},
	'es': {		
		'titulomissao':'Conquistador del Santuario',
		'title': 'Santuario Congelado',
		'detalhenormal':'Hay una etapa donde necesitas derrotar a todos los monstruos para destruir el piso y continuar.',
		'detalheheroico':'En el modo campeón, la misión se vuelve un poco más difícil, requiriendo derrotar a Arleoth al final.',
		'item2103840_nomedoitem':'Conquistador del Santuario',
		'item2103840_tipo':'Título',
		'item2103840_custo':'Cristal 0',		
		'item2103840_efeito1':'Ataque Especial +600',
		'item2103840_efeito2':'Defensa Especial +600',
		'item2103840_efeito3':'Daño Crítico +48.60%',
		'item2103840_efeito4':'Lanza Infernal +600'
	}
};

const TraducaoRefugio = {
	'en': {				
		'titulomissao':'Nephilim, The Lord of Devastation',
		'title': 'Forsaken Spirit Asylum',
		'detalhenormal':'Nephilim does not take damage until all three of his shields are destroyed. To do this, you must use basic attacks because skills and pets do not work on the shields. First, break the shields on both hands and then the chest shield. If you break the chest shield first, he will use a skill that will kill everyone. After breaking his shields, you will have a small window of time to deal damage to him.',
		'item2437480_nomedoitem':'Nephilim, The Lord of Devastation',
		'item2437480_tipo':'Title',
		'item2437480_custo':'Crystal 0',		
		'item2437480_efeito1':'Special Attack +3000',
		'item2437480_efeito2':'Special Defense +3000',
		'item2437480_efeito3':'Critical Damage +114.40%',
		'item2437480_efeito4':'Hell Spear +3000',
		'item2437480_efeito5':'Special Resistance +25.00%'
	},
	'pt': {		
		'titulomissao':'Nephilim, O Senhor da Devastação',
		'title': 'Refúgio Devastado dos Espíritos',
		'detalhenormal':'Nephilim é imune a dano até que todos os seus três escudos sejam destruídos. Para isso, você deve usar ataques básicos, pois habilidades e mascotes não funcionam contra os escudos. Primeiro, quebre os escudos das mãos e, em seguida, o escudo do peito. Se você quebrar o escudo do peito primeiro, ele usará uma habilidade que matará todos. Após destruir os escudos, você terá uma pequena janela de tempo para causar dano a ele.',
		'item2437480_nomedoitem':'Nephilim, O Senhor da Devastação',
		'item2437480_tipo':'Título',
		'item2437480_custo':'Cristal 0',		
		'item2437480_efeito1':'Ataque Especial +3000',
		'item2437480_efeito2':'Defesa Especial +3000',
		'item2437480_efeito3':'Dano Crítico +114.40%',
		'item2437480_efeito4':'Lança Infernal +3000',
		'item2437480_efeito5':'Resistência à status anormais +25.00%'			
	},
	'cn': {		
		'titulomissao':'尼非订，毁灭之主',
		'title': '被遗弃的灵魂避难所',
		'detalhenormal':'尼非订 在所有三个护盾被破坏之前不会受到伤害。为此，你必须使用基础攻击，因为技能和宠物对护盾不起作用。首先，打破双手的护盾，然后是胸部护盾。如果你先打破胸部护盾，他将使用一种技能，杀死所有人。打破护盾后，你会有一个小的时间窗口来对他造成伤害。',
		'item2437480_nomedoitem':'尼非订，毁灭之主',
		'item2437480_tipo':'头衔',
		'item2437480_custo':'水晶 0',		
		'item2437480_efeito1':'特殊攻击 +3000',
		'item2437480_efeito2':'特殊防御 +3000',
		'item2437480_efeito3':'暴击伤害 +114.40%',
		'item2437480_efeito4':'地狱矛 +3000',
		'item2437480_efeito5':'异常状态抵抗 +25.00%'
	},
	'ph': {		
		'titulomissao':'Nephilim, Panginoon ng Pagwasak',
		'title': 'Pinabayaan na Asilo ng Espiritu',
		'detalhenormal':'Hindi makakatanggap ng pinsala si Nephilim hanggang masira ang lahat ng tatlong kalasag niya. Para magawa ito, kailangan mong gumamit ng basic attacks dahil hindi gumagana ang mga kasanayan at alaga sa mga kalasag. Una, sirain ang mga kalasag sa parehong kamay at pagkatapos ay ang kalasag sa dibdib. Kung sirain mo muna ang kalasag sa dibdib, gagamit siya ng kasanayan na papatay sa lahat. Pagkatapos masira ang mga kalasag niya, magkakaroon ka ng maliit na oras upang magdulot ng pinsala sa kanya.',
		'item2437480_nomedoitem':'Nephilim, Panginoon ng Pagwasak',
		'item2437480_tipo':'Titulo',
		'item2437480_custo':'Kristal 0',		
		'item2437480_efeito1':'Espesyal na Atake +3000',
		'item2437480_efeito2':'Espesyal na Depensa +3000',
		'item2437480_efeito3':'Kritikal na Pinsala +114.40%',
		'item2437480_efeito4':'Impiyernong Sibat +3000',
		'item2437480_efeito5':'Resistensya sa Espesyal na Kondisyon +25.00%'
	},
	'th': {		
		'titulomissao':'เนฟิลิม, เจ้าแห่งการทำลายล้าง',
		'title': 'สถานที่ลี้ภัยวิญญาณที่ถูกทอดทิ้ง',
		'detalhenormal':'เนฟิลิม จะไม่รับความเสียหายจนกว่าทั้งสามโล่ของเขาจะถูกทำลาย ในการทำเช่นนี้คุณต้องใช้การโจมตีพื้นฐานเพราะทักษะและสัตว์เลี้ยงไม่ได้ผลกับโล่ ก่อนอื่นให้ทำลายโล่ที่มือทั้งสองข้างและจากนั้นก็โล่ที่หน้าอก หากคุณทำลายโล่หน้าอกก่อน เขาจะใช้ทักษะที่ฆ่าทุกคน หลังจากทำลายโล่ของเขา คุณจะมีเวลาสั้นๆในการทำให้เขาได้รับความเสียหาย',
		'item2437480_nomedoitem':'เนฟิลิม, เจ้าแห่งการทำลายล้าง',
		'item2437480_tipo':'ตำแหน่ง',
		'item2437480_custo':'คริสตัล 0',		
		'item2437480_efeito1':'การโจมตีพิเศษ +3000',
		'item2437480_efeito2':'การป้องกันพิเศษ +3000',
		'item2437480_efeito3':'ความเสียหายคริติคอล +114.40%',
		'item2437480_efeito4':'หอกนรก +3000',
		'item2437480_efeito5':'ความต้านทานพิเศษ +25.00%'
	},
	'id': {		
		'titulomissao':'Nephilim, Penguasa Kehancuran',		
		'detalhenormal':'Nephilim tidak akan menerima kerusakan hingga ketiga perisainya hancur. Untuk melakukan ini, Anda harus menggunakan serangan dasar karena keterampilan dan hewan peliharaan tidak bekerja pada perisai. Pertama, hancurkan perisai di kedua tangan lalu perisai dada. Jika Anda menghancurkan perisai dada terlebih dahulu, dia akan menggunakan keterampilan yang akan membunuh semua orang. Setelah menghancurkan perisainya, Anda akan memiliki jendela kecil waktu untuk memberikan kerusakan padanya.',
		'item2437480_nomedoitem':'Nephilim, Penguasa Kehancuran',
		'item2437480_tipo':'Gelar',
		'item2437480_custo':'Kristal 0'
	},
	'es': {		
		'titulomissao':'Nephilim, el Señor de la Devastación',
		'title': 'Asilo de Espíritus Abandonado',
		'detalhenormal':'Nephilim no recibe daño hasta que se destruyan sus tres escudos. Para hacer esto, debes usar ataques básicos porque las habilidades y las mascotas no funcionan en los escudos. Primero, rompe los escudos de ambas manos y luego el escudo del pecho. Si rompes primero el escudo del pecho, usará una habilidad que matará a todos. Después de romper sus escudos, tendrás una pequeña ventana de tiempo para hacerle daño.',
		'item2437480_nomedoitem':'Nephilim, el Señor de la Devastación',
		'item2437480_tipo':'Título',
		'item2437480_custo':'Cristal 0',		
		'item2437480_efeito1':'Ataque Especial +3000',
		'item2437480_efeito2':'Defensa Especial +3000',
		'item2437480_efeito3':'Daño Crítico +114.40%',
		'item2437480_efeito4':'Lanza Infernal +3000',
		'item2437480_efeito5':'Resistencia Especial +25.00%'
	}
};

const TraducaoBlitzchen = {
	'en': {
		'titulomissao':'Dragon Hunter',
		'title': 'Blitzchen Lair',
		'item1878980_nomedoitem':'Dragon Hunter',
		'item1878980_tipo':'Title',
		'item1878980_custo':'Crystal 0',		
		'item1878980_efeito1':'Special Attack +5000',
		'item1878980_efeito2':'Special Defense +5000',
		'item1878980_efeito3':'Critical Damage +100.00%',
		'item1878980_efeito4':'Hell Spear +1000'
	},
	'pt': {		
		'titulomissao':'Caçador de Dragões',
		'title': 'Covil de Blitzchen',		
		'item1878980_nomedoitem':'Caçador de Dragões',
		'item1878980_tipo':'Título',
		'item1878980_custo':'Cristal 0',
		'item1878980_efeito1':'Ataque Especial +5000',
		'item1878980_efeito2':'Defesa Especial +5000',
		'item1878980_efeito3':'Dano Crítico +100.00%',
		'item1878980_efeito4':'Lança Infernal +1000'
	},
	'cn': {		
		'titulomissao':'龙猎人',
		'title': 'Blitzchen 巢穴',		
		'item1878980_nomedoitem':'龙猎人',
		'item1878980_tipo':'头衔',
		'item1878980_custo':'水晶 0',
		'item1878980_efeito1':'特殊攻击 +5000',
		'item1878980_efeito2':'特殊防御 +5000',
		'item1878980_efeito3':'暴击伤害 +100.00%',
		'item1878980_efeito4':'地狱矛 +1000'
	},
	'ph': {		
		'titulomissao':'Dragon Hunter',
		'title': 'Blitzchen Lungga',		
		'item1878980_nomedoitem':'Dragon Hunter',
		'item1878980_tipo':'Titulo',
		'item1878980_custo':'Kristal 0',
		'item1878980_efeito1':'Espesyal na Atake +5000',
		'item1878980_efeito2':'Espesyal na Depensa +5000',
		'item1878980_efeito3':'Kritikal na Pinsala +100.00%',
		'item1878980_efeito4':'Impiyernong Sibat +1000'
	},
	'th': {		
		'titulomissao':'นักล่ามังกร',
		'title': 'ถ้ำ Blitzchen',		
		'item1878980_nomedoitem':'นักล่ามังกร',
		'item1878980_tipo':'ตำแหน่ง',
		'item1878980_custo':'คริสตัล 0',
		'item1878980_efeito1':'การโจมตีพิเศษ +5000',
		'item1878980_efeito2':'การป้องกันพิเศษ +5000',
		'item1878980_efeito3':'ความเสียหายคริติคอล +100.00%',
		'item1878980_efeito4':'หอกนรก +1000'
	},
	'id': {		
		'titulomissao':'Pemburu Naga',
		'item1878980_nomedoitem':'Pemburu Naga',
		'item1878980_tipo':'Gelar',
		'item1878980_custo':'Kristal 0'
	},
	'es': {		
		'titulomissao':'Cazador de Dragones',
		'title': 'Guarida de Blitzchen',		
		'item1878980_nomedoitem':'Cazador de Dragones',
		'item1878980_tipo':'Título',
		'item1878980_custo':'Cristal 0',
		'item1878980_efeito1':'Ataque Especial +5000',
		'item1878980_efeito2':'Defensa Especial +5000',
		'item1878980_efeito3':'Daño Crítico +100.00%',
		'item1878980_efeito4':'Lanza Infernal +1000'
	}
};

const TraducaoHades = {
	'en': {
		'titulomissao':'Hades\' Hell Survivor',
		'title': "Hades' Hell",
		'itemtitulohades_nomedoitem':'Hades\' Hell Survivor',
		'itemtitulohades_tipo':'Title',
		'itemtitulohades_custo':'Crystal 0',		
		'itemtitulohades_efeito1':'Special Attack +3000',
		'itemtitulohades_efeito2':'Special Defense +3000',
		'itemtitulohades_efeito3':'Critical Damage +30.00%',
		'itemtitulohades_efeito4':'Hell Spear +1000'
	},
	'pt': {		
		'titulomissao':'Sobrevivente do Inferno de Hades',
		'title': 'Domínio de Hades',		
		'itemtitulohades_nomedoitem':'Sobrevivente do Inferno de Hades',
		'itemtitulohades_tipo':'Título',
		'itemtitulohades_custo':'Cristal 0',
		'itemtitulohades_efeito1':'Ataque Especial +3000',
		'itemtitulohades_efeito2':'Defesa Especial +3000',
		'itemtitulohades_efeito3':'Dano Crítico +30.00%',
		'itemtitulohades_efeito4':'Lança Infernal +1000'
	},
	'cn': {		
		'titulomissao':'冥界幸存者',
		'title': '哈迪斯的地狱',		
		'itemtitulohades_nomedoitem':'冥界幸存者',
		'itemtitulohades_tipo':'头衔',
		'itemtitulohades_custo':'水晶 0',
		'itemtitulohades_efeito1':'特殊攻击 +3000',
		'itemtitulohades_efeito2':'特殊防御 +3000',
		'itemtitulohades_efeito3':'暴击伤害 +30.00%',
		'itemtitulohades_efeito4':'地狱矛 +1000'
	},
	'ph': {		
		'titulomissao':'Nakadaan sa Impiyerno ni Hades',
		'title': 'Impiyerno ni Hades',		
		'itemtitulohades_nomedoitem':'Nakadaan sa Impiyerno ni Hades',
		'itemtitulohades_tipo':'Titulo',
		'itemtitulohades_custo':'Kristal 0',
		'itemtitulohades_efeito1':'Espesyal na Atake +3000',
		'itemtitulohades_efeito2':'Espesyal na Depensa +3000',
		'itemtitulohades_efeito3':'Kritikal na Pinsala +30.00%',
		'itemtitulohades_efeito4':'Impiyernong Sibat +1000'
	},
	'th': {		
		'titulomissao':'ผู้รอดชีวิตจากนรกของฮาเดส',
		'title': 'นรกของฮาเดส',		
		'itemtitulohades_nomedoitem':'ผู้รอดชีวิตจากนรกของฮาเดส',
		'itemtitulohades_tipo':'ตำแหน่ง',
		'itemtitulohades_custo':'คริสตัล 0',
		'itemtitulohades_efeito1':'การโจมตีพิเศษ +3000',
		'itemtitulohades_efeito2':'การป้องกันพิเศษ +3000',
		'itemtitulohades_efeito3':'ความเสียหายคริติคอล +30.00%',
		'itemtitulohades_efeito4':'หอกนรก +1000'
	},
	'id': {		
		'titulomissao':'Penyintas Neraka Hades',
		'itemtitulohades_nomedoitem':'Penyintas Neraka Hades',
		'itemtitulohades_tipo':'Gelar',
		'itemtitulohades_custo':'Kristal 0'
	},
	'es': {		
		'titulomissao':'Sobreviviente del Infierno de Hades',
		'title': 'Infierno de Hades',		
		'itemtitulohades_nomedoitem':'Sobreviviente del Infierno de Hades',
		'itemtitulohades_tipo':'Título',
		'itemtitulohades_custo':'Cristal 0',
		'itemtitulohades_efeito1':'Ataque Especial +3000',
		'itemtitulohades_efeito2':'Defensa Especial +3000',
		'itemtitulohades_efeito3':'Daño Crítico +30.00%',
		'itemtitulohades_efeito4':'Lanza Infernal +1000'
	}
};

const TraducaoHenir = {
	'en': {
		'titulomissao':'The Otherworld Lord',
		'title': "Henir's Time and Space",
		'detalhenormal':'In the stages with the flying cube, you will have 30 seconds to destroy it before the mission concludes automatically.',
		'itemtitulohenir_nomedoitem':'The Otherworld Lord',
		'itemtitulohenir_tipo':'Title',
		'itemtitulohenir_custo':'Crystal 0',		
		'itemtitulohenir_efeito1':'Special Attack +800',
		'itemtitulohenir_efeito2':'Special Defense +800',
		'itemtitulohenir_efeito3':'Critical Damage +58.50%',
		'itemtitulohenir_efeito4':'Hell Spear +800',
		'itemtitulohenir_efeito5':'Special Resistance +10.00%'
	},
	'pt': {		
		'titulomissao':'O Senhor de Outro Mundo',
		'title': 'Tempo e Espaço de Henir',
		'detalhenormal':'Nos estágios com o cubo voador, você terá 30 segundos para destruí-lo antes que a missão seja concluída automaticamente.',
		'itemtitulohenir_nomedoitem':'O Senhor de Outro Mundo',
		'itemtitulohenir_tipo':'Título',
		'itemtitulohenir_custo':'Cristal 0',		
		'itemtitulohenir_efeito1':'Ataque Especial +800',
		'itemtitulohenir_efeito2':'Defesa Especial +800',
		'itemtitulohenir_efeito3':'Dano Crítico +58.50%',
		'itemtitulohenir_efeito4':'Lança Infernal +800',
		'itemtitulohenir_efeito5':'Resistência à status anormais +10.00%'
	},
	'cn': {		
		'titulomissao':'异界之主',
		'title': '亨尼尔的时空',
		'detalhenormal':'在有飞行立方体的阶段中，你有30秒时间摧毁它，否则任务将自动结束。',
		'itemtitulohenir_nomedoitem':'异界之主',
		'itemtitulohenir_tipo':'头衔',
		'itemtitulohenir_custo':'水晶 0',		
		'itemtitulohenir_efeito1':'特殊攻击 +800',
		'itemtitulohenir_efeito2':'特殊防御 +800',
		'itemtitulohenir_efeito3':'暴击伤害 +58.50%',
		'itemtitulohenir_efeito4':'地狱矛 +800',
		'itemtitulohenir_efeito5':'特殊抗性 +10.00%'
	},
	'ph': {		
		'titulomissao':'Panginoon ng Ibang Daigdig',
		'title': 'Oras at Espasyo ni Henir',
		'detalhenormal':'Sa mga yugto na may lumilipad na kubo, mayroon kang 30 segundo upang sirain ito bago awtomatikong matapos ang misyon.',
		'itemtitulohenir_nomedoitem':'Panginoon ng Ibang Daigdig',
		'itemtitulohenir_tipo':'Titulo',
		'itemtitulohenir_custo':'Kristal 0',		
		'itemtitulohenir_efeito1':'Espesyal na Atake +800',
		'itemtitulohenir_efeito2':'Espesyal na Depensa +800',
		'itemtitulohenir_efeito3':'Kritikal na Pinsala +58.50%',
		'itemtitulohenir_efeito4':'Impiyernong Sibat +800',
		'itemtitulohenir_efeito5':'Espesyal na Paglaban +10.00%'
	},
	'th': {		
		'titulomissao':'เจ้าแห่งโลกอื่น',
		'title': 'เวลาของ Henir และพื้นที่',
		'detalhenormal':'ในด่านที่มีลูกบาศก์บิน คุณมีเวลา 30 วินาทีในการทำลายมันก่อนที่ภารกิจจะสิ้นสุดโดยอัตโนมัติ',
		'itemtitulohenir_nomedoitem':'เจ้าแห่งโลกอื่น',
		'itemtitulohenir_tipo':'ตำแหน่ง',
		'itemtitulohenir_custo':'คริสตัล 0',		
		'itemtitulohenir_efeito1':'การโจมตีพิเศษ +800',
		'itemtitulohenir_efeito2':'การป้องกันพิเศษ +800',
		'itemtitulohenir_efeito3':'ความเสียหายคริติคอล +58.50%',
		'itemtitulohenir_efeito4':'หอกนรก +800',
		'itemtitulohenir_efeito5':'ความต้านทานพิเศษ +10.00%'
	},
	'id': {		
		'titulomissao':'Tuan Dunia Lain',		
		'detalhenormal':'Di tahap dengan kubus terbang, Anda memiliki 30 detik untuk menghancurkannya sebelum misi selesai secara otomatis.',
		'itemtitulohenir_nomedoitem':'Tuan Dunia Lain',
		'itemtitulohenir_tipo':'Gelar',
		'itemtitulohenir_custo':'Kristal 0'
	},
	'es': {		
		'titulomissao':'El Señor del Otro Mundo',
		'title': 'Tiempo y Espacio de Henir',
		'detalhenormal':'En las etapas con el cubo volador, tendrás 30 segundos para destruirlo antes de que la misión se concluya automáticamente.',
		'itemtitulohenir_nomedoitem':'El Señor del Otro Mundo',
		'itemtitulohenir_tipo':'Título',
		'itemtitulohenir_custo':'Cristal 0',		
		'itemtitulohenir_efeito1':'Ataque Especial +800',
		'itemtitulohenir_efeito2':'Defensa Especial +800',
		'itemtitulohenir_efeito3':'Daño Crítico +58.50%',
		'itemtitulohenir_efeito4':'Lanza Infernal +800',
		'itemtitulohenir_efeito5':'Resistencia Especial +10.00%'
	}
};

const TraducaoMD = {
	'en': {			
		'titulomissao':'Fallen Hero\'s Symbol',
		'title': "Dimensional Curse",
		'detalhenormal':'In each stage between bosses, a chest may spawn at the end of the stage with extra drops.',
		'detalheheroico':'In every stage between bosses, there is a chest with extra drops.',
		'itemtitulomd_nomedoitem':'Fallen Hero\'s Symbol',
		'itemtitulomd_tipo':'Title',
		'itemtitulomd_custo':'Crystal 0',		
		'itemtitulomd_efeito1':'Special Attack +400',
		'itemtitulomd_efeito2':'Special Defense +400',
		'itemtitulomd_efeito3':'Critical Damage +37.50%',
		'itemtitulomd_efeito4':'Hell Spear +400'		
	},
	'pt': {		
		'titulomissao':'Símbolo do Herói Caído',
		'title': 'Maldição Dimensional',
		'detalhenormal':'Em cada estágio entre chefes pode nascer um baú no final do estágio com drops extras.',
		'detalheheroico':'Em todo estágio entre chefes tem um baú com drops extras.',
		'itemtitulomd_nomedoitem':'Símbolo do Herói Caído',
		'itemtitulomd_tipo':'Título',
		'itemtitulomd_custo':'Cristal 0',		
		'itemtitulomd_efeito1':'Ataque Especial +400',
		'itemtitulomd_efeito2':'Defesa Especial +400',
		'itemtitulomd_efeito3':'Dano Crítico +37.50%',
		'itemtitulomd_efeito4':'Lança Infernal +400'
	},
	'es': {
		'titulomissao':'Símbolo del Héroe Caído',
		'title': 'Maldición Dimensional',
		'detalhenormal':'En cada etapa entre jefes, puede aparecer un cofre al final de la etapa con drops extras.',
		'detalheheroico':'En cada etapa entre jefes hay un cofre con drops extras.',
		'itemtitulomd_nomedoitem':'Símbolo del Héroe Caído',
		'itemtitulomd_tipo':'Título',
		'itemtitulomd_custo':'Cristal 0',		
		'itemtitulomd_efeito1':'Ataque Especial +400',
		'itemtitulomd_efeito2':'Defensa Especial +400',
		'itemtitulomd_efeito3':'Daño Crítico +37.50%',
		'itemtitulomd_efeito4':'Lanza Infernal +400'
	},
	'ph': {
		'titulomissao':'Simbolo ng Nalugmok na Bayani',
		'title': 'Dimensiyonal na Sumpa',
		'detalhenormal':'Sa bawat yugto sa pagitan ng mga boss, maaaring lumitaw ang isang dibdib sa dulo ng yugto na may mga dagdag na drop.',
		'detalheheroico':'Sa bawat yugto sa pagitan ng mga boss ay may isang dibdib na may mga dagdag na drop.',
		'itemtitulomd_nomedoitem':'Simbolo ng Nalugmok na Bayani',
		'itemtitulomd_tipo':'Titulo',
		'itemtitulomd_custo':'Kristal 0',		
		'itemtitulomd_efeito1':'Espesyal na Pag-atake +400',
		'itemtitulomd_efeito2':'Espesyal na Depensa +400',
		'itemtitulomd_efeito3':'Kritikal na Pinsala +37.50%',
		'itemtitulomd_efeito4':'Lansang Impiyerno +400'
	},
	'cn': {
		'titulomissao':'堕落英雄的象征',
		'title': '次元诅咒',
		'detalhenormal':'在每个boss之间的阶段中，可能会在阶段末端出现一个带有额外掉落的宝箱。',
		'detalheheroico':'在每个boss之间的阶段中有一个带有额外掉落的宝箱。',
		'itemtitulomd_nomedoitem':'堕落英雄的象征',
		'itemtitulomd_tipo':'头衔',
		'itemtitulomd_custo':'水晶 0',		
		'itemtitulomd_efeito1':'特殊攻击 +400',
		'itemtitulomd_efeito2':'特殊防御 +400',
		'itemtitulomd_efeito3':'暴击伤害 +37.50%',
		'itemtitulomd_efeito4':'地狱之矛 +400'
	},
	'id': {
		'titulomissao':'Simbol Pahlawan Jatuh',		
		'detalhenormal':'Di setiap tahap antara bos, peti dapat muncul di akhir tahap dengan tambahan drop.',
		'detalheheroico':'Di setiap tahap antara bos ada peti dengan tambahan drop.',
		'itemtitulomd_nomedoitem':'Simbol Pahlawan Jatuh',
		'itemtitulomd_tipo':'Gelar',
		'itemtitulomd_custo':'Kristal 0'
	},
	'th': {
		'titulomissao':'สัญลักษณ์ของวีรบุรุษที่ร่วงหล่น',
		'title': 'คำสาปมิติ',
		'detalhenormal':'ในแต่ละด่านระหว่างบอสอาจมีหีบเกิดขึ้นที่ท้ายด่านพร้อมไอเทมดรอปพิเศษ',
		'detalheheroico':'ในทุกด่านระหว่างบอสจะมีหีบพร้อมไอเทมดรอปพิเศษ',
		'itemtitulomd_nomedoitem':'สัญลักษณ์ของวีรบุรุษที่ร่วงหล่น',
		'itemtitulomd_tipo':'ตำแหน่ง',
		'itemtitulomd_custo':'คริสตัล 0',		
		'itemtitulomd_efeito1':'การโจมตีพิเศษ +400',
		'itemtitulomd_efeito2':'การป้องกันพิเศษ +400',
		'itemtitulomd_efeito3':'ความเสียหายจากการโจมตีอย่างแรง +37.50%',
		'itemtitulomd_efeito4':'หอกนรก +400'
	}
};

const TraducaoSacrario = {
	'en': {				
		'title': "Spirit Sanctum",
		'detalhenormal':'When Ventus reaches half of his health, he becomes invulnerable and summons Lincy to assist him. Only after defeating Lincy can Ventus be attacked again.',
		'detalheheroico':"<strong>Ventus now has two phases.</strong><br><br><strong>Phase One:</strong><br>When Ventus reaches half of his health, he becomes invulnerable and summons Lincy to assist him. Only after defeating Lincy can Ventus be attacked again.<br><br><strong>Phase Two:</strong><br>Ventus merges with Lincy, enhancing his abilities. All players receive a debuff that disables critical damage against him. After 20 of Ventus's moves, he can be attacked to enter the Penalty state. In the Penalty state, players lose the critical damage debuff, and Ventus takes extra damage. If Ventus is not defeated during this time, players must wait for another 20 moves to attack him again.",
		'titulomissao1':'Ventus,The Wind Master',
		'itemtitulosacrario1_nomedoitem':'Ventus,The Wind Master',
		'itemtitulosacrario1_tipo':'Title',
		'itemtitulosacrario1_custo':'Crystal 0',		
		'itemtitulosacrario1_efeito1':'Special Attack +2000',
		'itemtitulosacrario1_efeito2':'Special Defense +2000',
		'itemtitulosacrario1_efeito3':'Critical Damage +91.50%',
		'itemtitulosacrario1_efeito4':'Hell Spear +2000',
		'itemtitulosacrario1_efeito5':'Special Resistance +10.00%',
		'titulomissao2':'Ventus,The Wind Master (Merged)',
		'itemtitulosacrario2_nomedoitem':'Ventus,The Wind Master (Merged)',
		'itemtitulosacrario2_tipo':'Title',
		'itemtitulosacrario2_custo':'Crystal 0',		
		'itemtitulosacrario2_efeito1':'Special Attack +4000',
		'itemtitulosacrario2_efeito2':'Special Defense +4000',
		'itemtitulosacrario2_efeito3':'Critical Damage +143.00%',
		'itemtitulosacrario2_efeito4':'Hell Spear +4000',
		'itemtitulosacrario2_efeito5':'Corruption Resistance +100',
		'itemtitulosacrario2_efeito6':'Special Resistance +30.00%'
	},
	'pt': {		
		'title': 'Sacrário dos Espíritos',
		'detalhenormal':'Quando Ventus atinge metade de sua vida, ele se torna invulnerável e invoca Lincy para ajudá-lo. Somente após derrotar Lincy, Ventus pode ser atacado novamente.',
		'detalheheroico':'<strong>Ventus agora possui duas fases.</strong><br><br><strong>Primeira Fase:</strong><br>Quando Ventus atinge metade de sua vida, ele se torna invulnerável e invoca Lincy para ajudá-lo. Somente após derrotar Lincy, Ventus pode ser atacado novamente.<br><br><strong>Segunda Fase:</strong><br>Ventus se funde com Lincy, melhorando suas habilidades. Todos os jogadores recebem um debuff que desativa o dano crítico causado nele. Após 20 movimentos de Ventus, ele pode ser atacado para entrar no estado de Penalty. No estado de Penalty, os jogadores perdem o debuff de não poder causar dano crítico e Ventus recebe dano extra. Se Ventus não for derrotado durante esse tempo, será necessário esperar mais 20 movimentos para poder atacá-lo novamente.',
		'titulomissao1':'Ventus, o Mestre do Vento',
		'itemtitulosacrario1_nomedoitem':'Ventus, o Mestre do Vento',
		'itemtitulosacrario1_tipo':'Título',
		'itemtitulosacrario1_custo':'Cristal 0',		
		'itemtitulosacrario1_efeito1':'Ataque Especial +2000',
		'itemtitulosacrario1_efeito2':'Defesa Especial +2000',
		'itemtitulosacrario1_efeito3':'Dano Crítico +91.50%',
		'itemtitulosacrario1_efeito4':'Lança Infernal +2000',
		'itemtitulosacrario1_efeito5':'Resistência à status anormais +25.00%',
		'titulomissao2':'Ventus, o Mestre do Vento (Transformado)',
		'itemtitulosacrario2_nomedoitem':'Ventus, o Mestre do Vento (Transformado)',
		'itemtitulosacrario2_tipo':'Título',
		'itemtitulosacrario2_custo':'Cristal 0',		
		'itemtitulosacrario2_efeito1':'Ataque Especial +4000',
		'itemtitulosacrario2_efeito2':'Defesa Especial +4000',
		'itemtitulosacrario2_efeito3':'Dano Crítico +143.00%',
		'itemtitulosacrario2_efeito4':'Lança Infernal +4000',
		'itemtitulosacrario2_efeito5':'Resistência a Corrupção +100',
		'itemtitulosacrario2_efeito6':'Resistência à status anormais +30.00%'
	},
	'cn': {				
		'title': '灵魂圣殿',
		'detalhenormal':'当维恩图斯的血量达到一半时，他会变得无敌并召唤林西来帮助他。只有击败林西后才能再次攻击维恩图斯。',
		'detalheheroico':'<strong>维恩图斯现在有两个阶段。</strong><br><br><strong>第一阶段：</strong><br>当维恩图斯的血量达到一半时，他会变得无敌并召唤林西来帮助他。只有击败林西后才能再次攻击维恩图斯。<br><br><strong>第二阶段：</strong><br>维恩图斯与林西融合，增强了他的能力。所有玩家会受到一个debuff，使其无法对他造成暴击伤害。在维恩图斯进行20次攻击后，可以对其进行攻击，使其进入Penalty状态。在Penalty状态下，玩家失去无法造成暴击伤害的debuff，维恩图斯受到额外伤害。如果在此期间未能击败维恩图斯，玩家必须再等待20次攻击后才能再次攻击他。',
		'titulomissao1':'风之大师维恩图斯',
		'itemtitulosacrario1_nomedoitem':'风之大师维恩图斯',
		'itemtitulosacrario1_tipo':'称号',
		'itemtitulosacrario1_custo':'水晶 0',		
		'itemtitulosacrario1_efeito1':'特殊攻击 +2000',
		'itemtitulosacrario1_efeito2':'特殊防御 +2000',
		'itemtitulosacrario1_efeito3':'暴击伤害 +91.50%',
		'itemtitulosacrario1_efeito4':'地狱矛 +2000',
		'itemtitulosacrario1_efeito5':'特殊抗性 +10.00%',
		'titulomissao2':'融合的风之大师维恩图斯',
		'itemtitulosacrario2_nomedoitem':'融合的风之大师维恩图斯',
		'itemtitulosacrario2_tipo':'称号',
		'itemtitulosacrario2_custo':'水晶 0',		
		'itemtitulosacrario2_efeito1':'特殊攻击 +4000',
		'itemtitulosacrario2_efeito2':'特殊防御 +4000',
		'itemtitulosacrario2_efeito3':'暴击伤害 +143.00%',
		'itemtitulosacrario2_efeito4':'地狱矛 +4000',
		'itemtitulosacrario2_efeito5':'腐化抗性 +100',
		'itemtitulosacrario2_efeito6':'特殊抗性 +30.00%'
	},
	'ph': {				
		'title': 'Sanctum ng Espiritu',
		'detalhenormal':'Kapag umabot na sa kalahati ng kanyang kalusugan si Ventus, nagiging invulnerable siya at tinatawag si Lincy upang tulungan siya. Pagkatapos lamang matalo si Lincy ay maaaring atakihin muli si Ventus.',
		'detalheheroico':'<strong>Ngayon ay may dalawang yugto si Ventus.</strong><br><br><strong>Unang Yugto:</strong><br>Kapag umabot na sa kalahati ng kanyang kalusugan si Ventus, nagiging invulnerable siya at tinatawag si Lincy upang tulungan siya. Pagkatapos lamang matalo si Lincy ay maaaring atakihin muli si Ventus.<br><br><strong>Ikalawang Yugto:</strong><br>Nagpapalit si Ventus kay Lincy, nagpapahusay ng kanyang mga kakayahan. Lahat ng mga manlalaro ay tumatanggap ng isang debuff na nagtatanggal ng critical na pinsala laban sa kanya. Pagkatapos ng 20 kilos ni Ventus, maaaring siyang atakihin upang makapasok sa Penalty state. Sa Penalty state, nawawala ang critical damage debuff ng mga manlalaro, at si Ventus ay tumatanggap ng dagdag na pinsala. Kung hindi natalo si Ventus sa panahong ito, kailangang maghintay ang mga manlalaro ng isa pang 20 kilos upang muli siyang atakihin.',
		'titulomissao1':'Ventus, Ang Panginoon ng Hangin',
		'itemtitulosacrario1_nomedoitem':'Ventus, Ang Panginoon ng Hangin',
		'itemtitulosacrario1_tipo':'Pamagat',
		'itemtitulosacrario1_custo':'Kristal 0',		
		'itemtitulosacrario1_efeito1':'Special Attack +2000',
		'itemtitulosacrario1_efeito2':'Special Defense +2000',
		'itemtitulosacrario1_efeito3':'Critical Damage +91.50%',
		'itemtitulosacrario1_efeito4':'Hell Spear +2000',
		'itemtitulosacrario1_efeito5':'Special Resistance +10.00%',
		'titulomissao2':'Ventus, Ang Panginoon ng Hangin (Pinagsama)',
		'itemtitulosacrario2_nomedoitem':'Ventus, Ang Panginoon ng Hangin (Pinagsama)',
		'itemtitulosacrario2_tipo':'Pamagat',
		'itemtitulosacrario2_custo':'Kristal 0',		
		'itemtitulosacrario2_efeito1':'Special Attack +4000',
		'itemtitulosacrario2_efeito2':'Special Defense +4000',
		'itemtitulosacrario2_efeito3':'Critical Damage +143.00%',
		'itemtitulosacrario2_efeito4':'Hell Spear +4000',
		'itemtitulosacrario2_efeito5':'Corruption Resistance +100',
		'itemtitulosacrario2_efeito6':'Special Resistance +30.00%'
	},
	'th': {				
		'title': 'เขตรักษาวิญญาณ',
		'detalhenormal':'เมื่อเวนทัสถึงครึ่งหนึ่งของสุขภาพ เขาจะกลายเป็นอมตะและเรียกลินซีมาช่วยเขา ต้องกำจัดลินซีก่อนจึงจะสามารถโจมตีเวนทัสได้อีกครั้ง',
		'detalheheroico':'<strong>เวนทัสมีสองเฟสแล้ว</strong><br><br><strong>เฟสแรก:</strong><br>เมื่อเวนทัสถึงครึ่งหนึ่งของสุขภาพ เขาจะกลายเป็นอมตะและเรียกลินซีมาช่วยเขา ต้องกำจัดลินซีก่อนจึงจะสามารถโจมตีเวนทัสได้อีกครั้ง<br><br><strong>เฟสสอง:</strong><br>เวนทัสรวมร่างกับลินซี เพิ่มพลังความสามารถของเขา ผู้เล่นทุกคนจะได้รับดีบัฟที่ทำให้ไม่สามารถทำความเสียหายคริติคอลต่อเขาได้ หลังจากการเคลื่อนไหวของเวนทัส 20 ครั้ง เขาจะถูกโจมตีเพื่อเข้าสู่สถานะ Penalty ในสถานะ Penalty ผู้เล่นจะสูญเสียดีบัฟที่ไม่สามารถทำความเสียหายคริติคอล และเวนทัสจะได้รับความเสียหายเพิ่มเติม หากไม่สามารถกำจัดเวนทัสในช่วงเวลานี้ได้ ต้องรออีก 20 การเคลื่อนไหวเพื่อโจมตีเขาอีกครั้ง',
		'titulomissao1':'เวนทัส จ้าวแห่งสายลม',
		'itemtitulosacrario1_nomedoitem':'เวนทัส จ้าวแห่งสายลม',
		'itemtitulosacrario1_tipo':'ชื่อ',
		'itemtitulosacrario1_custo':'คริสตัล 0',		
		'itemtitulosacrario1_efeito1':'การโจมตีพิเศษ +2000',
		'itemtitulosacrario1_efeito2':'การป้องกันพิเศษ +2000',
		'itemtitulosacrario1_efeito3':'ความเสียหายคริติคอล +91.50%',
		'itemtitulosacrario1_efeito4':'หอกนรก +2000',
		'itemtitulosacrario1_efeito5':'ความต้านทานพิเศษ +10.00%',
		'titulomissao2':'เวนทัส จ้าวแห่งสายลม (รวมร่าง)',
		'itemtitulosacrario2_nomedoitem':'เวนทัส จ้าวแห่งสายลม (รวมร่าง)',
		'itemtitulosacrario2_tipo':'ชื่อ',
		'itemtitulosacrario2_custo':'คริสตัล 0',		
		'itemtitulosacrario2_efeito1':'การโจมตีพิเศษ +4000',
		'itemtitulosacrario2_efeito2':'การป้องกันพิเศษ +4000',
		'itemtitulosacrario2_efeito3':'ความเสียหายคริติคอล +143.00%',
		'itemtitulosacrario2_efeito4':'หอกนรก +4000',
		'itemtitulosacrario2_efeito5':'ความต้านทานต่อการทุจริต +100',
		'itemtitulosacrario2_efeito6':'ความต้านทานพิเศษ +30.00%'
	},
	'id': {
		'detalhenormal':'Ketika Ventus mencapai setengah dari kesehatannya, dia menjadi kebal dan memanggil Lincy untuk membantunya. Hanya setelah mengalahkan Lincy, Ventus dapat diserang lagi.',
		'detalheheroico':'<strong>Ventus sekarang memiliki dua fase.</strong><br><br><strong>Fase Pertama:</strong><br>Ketika Ventus mencapai setengah dari kesehatannya, dia menjadi kebal dan memanggil Lincy untuk membantunya. Hanya setelah mengalahkan Lincy, Ventus dapat diserang lagi.<br><br><strong>Fase Kedua:</strong><br>Ventus menyatu dengan Lincy, meningkatkan kemampuannya. Semua pemain menerima debuff yang menonaktifkan kerusakan kritis terhadapnya. Setelah 20 gerakan Ventus, dia dapat diserang untuk memasuki keadaan Penalty. Dalam keadaan Penalty, pemain kehilangan debuff kerusakan kritis, dan Ventus menerima kerusakan tambahan. Jika Ventus tidak dikalahkan selama waktu ini, pemain harus menunggu 20 gerakan lagi untuk menyerangnya kembali.',
		'titulomissao1':'Ventus, Sang Penguasa Angin',
		'itemtitulosacrario1_nomedoitem':'Ventus, Sang Penguasa Angin',
		'itemtitulosacrario1_tipo':'Judul',
		'itemtitulosacrario1_custo':'Kristal 0',
		'titulomissao2':'Ventus, Sang Penguasa Angin (Bergabung)',
		'itemtitulosacrario2_nomedoitem':'Ventus, Sang Penguasa Angin (Bergabung)',
		'itemtitulosacrario2_tipo':'Judul',
		'itemtitulosacrario2_custo':'Kristal 0'
	},
	'es': {
		'title': 'Santuario de los Espíritus',
		'detalhenormal': 'Cuando Ventus alcanza la mitad de su vida, se vuelve invulnerable e invoca a Lincy para que lo ayude. Solo después de derrotar a Lincy, Ventus puede ser atacado nuevamente.',
		'detalheheroico': '<strong>Ventus ahora tiene dos fases.</strong><br><br><strong>Primera Fase:</strong><br>Cuando Ventus alcanza la mitad de su vida, se vuelve invulnerable e invoca a Lincy para que lo ayude. Solo después de derrotar a Lincy, Ventus puede ser atacado nuevamente.<br><br><strong>Segunda Fase:</strong><br>Ventus se fusiona con Lincy, mejorando sus habilidades. Todos los jugadores reciben un debuff que desactiva el daño crítico contra él. Después de 20 movimientos de Ventus, se le puede atacar para entrar en el estado de Penalty. En el estado de Penalty, los jugadores pierden el debuff de daño crítico y Ventus recibe daño extra. Si Ventus no es derrotado durante este tiempo, los jugadores deben esperar otros 20 movimientos para atacarlo nuevamente.',
		'titulomissao1': 'Ventus, El Maestro del Viento',
		'itemtitulosacrario1_nomedoitem': 'Ventus, El Maestro del Viento',
		'itemtitulosacrario1_tipo': 'Título',
		'itemtitulosacrario1_custo': 'Cristal 0',		
		'itemtitulosacrario1_efeito1': 'Ataque Especial +2000',
		'itemtitulosacrario1_efeito2': 'Defensa Especial +2000',
		'itemtitulosacrario1_efeito3': 'Daño Crítico +91.50%',
		'itemtitulosacrario1_efeito4': 'Lanza Infernal +2000',
		'itemtitulosacrario1_efeito5': 'Resistencia Especial +10.00%',
		'titulomissao2': 'Ventus, El Maestro del Viento (Fusionado)',
		'itemtitulosacrario2_nomedoitem': 'Ventus, El Maestro del Viento (Fusionado)',
		'itemtitulosacrario2_tipo': 'Título',
		'itemtitulosacrario2_custo': 'Cristal 0',		
		'itemtitulosacrario2_efeito1': 'Ataque Especial +4000',
		'itemtitulosacrario2_efeito2': 'Defensa Especial +4000',
		'itemtitulosacrario2_efeito3': 'Daño Crítico +143.00%',
		'itemtitulosacrario2_efeito4': 'Resistencia a la Corrupción +100',
		'itemtitulosacrario2_efeito6': 'Resistencia Especial +30.00%'
	}
};

const TraducaoReigosma = {
	'en': {				
		'title': 'King Slime'		
	},
	'pt': {				
		'title': 'Rei Gosma'
	},
	'cn': {				
		'title': '史莱姆王'
	},
	'ph': {				
		'title': 'Hari ng Slime'
	},
	'th': {				
		'title': 'ราชาสไลม์'
	},
	'es': {				
		'title': 'Rey Baba'
	}
};

const TraducaoAltar = {
	'en': {				
		'titulomissao':'Lenora, Guardian of the Portal',
		'title': "Altar of Invocation",
		'itemtituloaltar_nomedoitem':'Lenora, Guardian of the Portal',		
		'itemtituloaltar_tipo':'Title',
		'itemtituloaltar_custo':'Crystal 0',		
		'itemtituloaltar_efeito1':'Special Attack +1000',
		'itemtituloaltar_efeito2':'Special Defense +1000',
		'itemtituloaltar_efeito3':'Critical Damage +73.20%',
		'itemtituloaltar_efeito4':'Hell Spear +1000',
		'itemtituloaltar_efeito5':'Special Resistance +22.00%'
	},
	'pt': {		
		'titulomissao':'Lenora, A Guardiã do Portal',
		'title': 'Altar da Invocação',	
		'itemtituloaltar_nomedoitem':'Lenora, A Guardiã do Portal',
		'itemtituloaltar_tipo':'Título',
		'itemtituloaltar_custo':'Cristal 0',		
		'itemtituloaltar_efeito1':'Ataque Especial +1000',
		'itemtituloaltar_efeito2':'Defesa Especial +1000',
		'itemtituloaltar_efeito3':'Dano Crítico +73.20%',
		'itemtituloaltar_efeito4':'Lança Infernal +1000',
		'itemtituloaltar_efeito5':'Resistência à status anormais +22.00%'
	},
	'cn': {		
		'titulomissao':'传送门守护者莱诺拉',
		'title': '召唤祭坛',	
		'itemtituloaltar_nomedoitem':'传送门守护者莱诺拉',
		'itemtituloaltar_tipo':'头衔',
		'itemtituloaltar_custo':'水晶 0',		
		'itemtituloaltar_efeito1':'特殊攻击 +1000',
		'itemtituloaltar_efeito2':'特殊防御 +1000',
		'itemtituloaltar_efeito3':'暴击伤害 +73.20%',
		'itemtituloaltar_efeito4':'地狱矛 +1000',
		'itemtituloaltar_efeito5':'特殊抗性 +22.00%'
	},
	'ph': {		
		'titulomissao':'Lenora, Ang Tagapangalaga ng Portal',
		'title': 'Altar ng Pagtawag',	
		'itemtituloaltar_nomedoitem':'Lenora, Ang Tagapangalaga ng Portal',
		'itemtituloaltar_tipo':'Titulo',
		'itemtituloaltar_custo':'Kristal 0',		
		'itemtituloaltar_efeito1':'Espesyal na Atake +1000',
		'itemtituloaltar_efeito2':'Espesyal na Depensa +1000',
		'itemtituloaltar_efeito3':'Kritikal na Pinsala +73.20%',
		'itemtituloaltar_efeito4':'Impiyernong Sibat +1000',
		'itemtituloaltar_efeito5':'Espesyal na Paglaban +22.00%'
	},
	'th': {		
		'titulomissao':'เลโนรา ผู้พิทักษ์ประตูมิติ',
		'title': 'แท่นบูชาการอัญเชิญ',	
		'itemtituloaltar_nomedoitem':'เลโนรา ผู้พิทักษ์ประตูมิติ',
		'itemtituloaltar_tipo':'ตำแหน่ง',
		'itemtituloaltar_custo':'คริสตัล 0',		
		'itemtituloaltar_efeito1':'การโจมตีพิเศษ +1000',
		'itemtituloaltar_efeito2':'การป้องกันพิเศษ +1000',
		'itemtituloaltar_efeito3':'ความเสียหายคริติคอล +73.20%',
		'itemtituloaltar_efeito4':'หอกนรก +1000',
		'itemtituloaltar_efeito5':'ความต้านทานพิเศษ +22.00%'
	},
	'id': {		
		'titulomissao':'Lenora, Penjaga Portal',
		'itemtituloaltar_nomedoitem':'Lenora, Penjaga Portal',
		'itemtituloaltar_tipo':'Gelar',
		'itemtituloaltar_custo':'Kristal 0'
	},
	'es': {		
		'titulomissao':'Lenora, La Guardiana del Portal',
		'title': 'Altar de Invocación',	
		'itemtituloaltar_nomedoitem':'Lenora, La Guardiana del Portal',
		'itemtituloaltar_tipo':'Título',
		'itemtituloaltar_custo':'Cristal 0',		
		'itemtituloaltar_efeito1':'Ataque Especial +1000',
		'itemtituloaltar_efeito2':'Defensa Especial +1000',
		'itemtituloaltar_efeito3':'Daño Crítico +73.20%',
		'itemtituloaltar_efeito4':'Lanza Infernal +1000',
		'itemtituloaltar_efeito5':'Resistencia Especial +22.00%'
	}
};

const TraducaoVazioinvasao = {
	'en': {				
		'title': 'Void (Invasion)',
		'detalhenormal': 'The boss has no complicated mechanics. Back attack is recommended for more damage.',
		'detalheheroico': 'The boss has no complicated mechanics. Back attack is recommended for more damage.<br/>Now the boss has a fourth phase, making it more challenging.',
		'titulomissao':'Beginning of Chaos',
		'itemtitulovazioinvasao_nomedoitem':'Beginning of Chaos',
		'itemtitulovazioinvasao_tipo':'Title',
		'itemtitulovazioinvasao_custo':'Crystal 0',		
		'itemtitulovazioinvasao_efeito1':'Special Attack +5000',
		'itemtitulovazioinvasao_efeito2':'Special Defense +5000',
		'itemtitulovazioinvasao_efeito3':'Critical Damage +178.80%',
		'itemtitulovazioinvasao_efeito4':'Hell Spear +5000',
		'itemtitulovazioinvasao_efeito5':'Corruption Resistance +125',
		'itemtitulovazioinvasao_efeito6':'Special Resistance +30.00%'
	},
	'pt': {				
		'title': 'Vazio (Invasão)',
		'detalhenormal': 'O chefe não possui mecânicas complicadas. Atacar pelas costas dele é recomendado para causar mais dano.',
		'detalheheroico': 'O chefe não possui mecânicas complicadas. Atacar pelas costas dele é recomendado para causar mais dano.<br/>No modo heróico, o chefe se torna mais difícil com a adição de uma quarta fase.',
		'titulomissao':'Início do Caos',
		'itemtitulovazioinvasao_nomedoitem':'Início do Caos',
		'itemtitulovazioinvasao_tipo':'Título',
		'itemtitulovazioinvasao_custo':'Cristal 0',		
		'itemtitulovazioinvasao_efeito1':'Ataque Especial +5000',
		'itemtitulovazioinvasao_efeito2':'Defesa Especial +5000',
		'itemtitulovazioinvasao_efeito3':'Dano Crítico +178.80%',
		'itemtitulovazioinvasao_efeito4':'Lança Infernal +5000',
		'itemtitulovazioinvasao_efeito5':'Resistência a Corrupção +125',
		'itemtitulovazioinvasao_efeito6':'Resistência à status anormais +30.00%'
	},
	'cn': {				
		'title': '虚空（入侵）',
		'detalhenormal': 'Boss没有复杂的机制。推荐从后方攻击以造成更多伤害。',
		'detalheheroico': 'Boss没有复杂的机制。推荐从后方攻击以造成更多伤害。<br/>现在Boss有了第四阶段，使其更具挑战性。',
		'titulomissao':'混沌的开始',
		'itemtitulovazioinvasao_nomedoitem':'混沌的开始',
		'itemtitulovazioinvasao_tipo':'称号',
		'itemtitulovazioinvasao_custo':'水晶 0',		
		'itemtitulovazioinvasao_efeito1':'特殊攻击 +5000',
		'itemtitulovazioinvasao_efeito2':'特殊防御 +5000',
		'itemtitulovazioinvasao_efeito3':'暴击伤害 +178.80%',
		'itemtitulovazioinvasao_efeito4':'地狱矛 +5000',
		'itemtitulovazioinvasao_efeito5':'腐化抗性 +125',
		'itemtitulovazioinvasao_efeito6':'特殊抗性 +30.00%'
	},
	'ph': {				
		'title': 'Void (Invasion)',
		'detalhenormal': 'Ang boss ay walang kumplikadong mekanika. Inirerekomenda ang back attack para sa mas malaking pinsala.',
		'detalheheroico': 'Ang boss ay walang kumplikadong mekanika. Inirerekomenda ang back attack para sa mas malaking pinsala.<br/>Ngayon ay may ika-apat na yugto ang boss, na ginagawang mas mapaghamon.',
		'titulomissao':'Simula ng Kaguluhan',
		'itemtitulovazioinvasao_nomedoitem':'Simula ng Kaguluhan',
		'itemtitulovazioinvasao_tipo':'Titulo',
		'itemtitulovazioinvasao_custo':'Kristal 0',		
		'itemtitulovazioinvasao_efeito1':'Espesyal na Atake +5000',
		'itemtitulovazioinvasao_efeito2':'Espesyal na Depensa +5000',
		'itemtitulovazioinvasao_efeito3':'Kritikal na Pinsala +178.80%',
		'itemtitulovazioinvasao_efeito4':'Impiyernong Sibat +5000',
		'itemtitulovazioinvasao_efeito5':'Tibay laban sa Korapsyon +125',
		'itemtitulovazioinvasao_efeito6':'Espesyal na Paglaban +30.00%'
	},
	'th': {				
		'title': 'ช่องว่าง (การรุกราน)',
		'detalhenormal': 'บอสไม่มีกลไกที่ซับซ้อน แนะนำให้โจมตีด้านหลังเพื่อให้ได้รับความเสียหายมากขึ้น',
		'detalheheroico': 'บอสไม่มีกลไกที่ซับซ้อน แนะนำให้โจมตีด้านหลังเพื่อให้ได้รับความเสียหายมากขึ้น<br/>ตอนนี้บอสมีระยะที่สี่ทำให้ท้าทายยิ่งขึ้น',
		'titulomissao':'จุดเริ่มต้นของความโกลาหล',
		'itemtitulovazioinvasao_nomedoitem':'จุดเริ่มต้นของความโกลาหล',
		'itemtitulovazioinvasao_tipo':'ตำแหน่ง',
		'itemtitulovazioinvasao_custo':'คริสตัล 0',		
		'itemtitulovazioinvasao_efeito1':'การโจมตีพิเศษ +5000',
		'itemtitulovazioinvasao_efeito2':'การป้องกันพิเศษ +5000',
		'itemtitulovazioinvasao_efeito3':'ความเสียหายคริติคอล +178.80%',
		'itemtitulovazioinvasao_efeito4':'หอกนรก +5000',
		'itemtitulovazioinvasao_efeito5':'ความต้านทานการทุจริต +125',
		'itemtitulovazioinvasao_efeito6':'ความต้านทานพิเศษ +30.00%'
	},
	'id': {
		'detalhenormal': 'Bos tidak memiliki mekanik yang rumit. Serangan belakang dianjurkan untuk lebih banyak kerusakan.',
		'detalheheroico': 'Bos tidak memiliki mekanik yang rumit. Serangan belakang dianjurkan untuk lebih banyak kerusakan.<br/>Sekarang bos memiliki fase keempat, membuatnya lebih menantang.',
		'titulomissao':'Awal Kekacauan',
		'itemtitulovazioinvasao_nomedoitem':'Awal Kekacauan',
		'itemtitulovazioinvasao_tipo':'Gelar',
		'itemtitulovazioinvasao_custo':'Kristal 0'
	},
	'es': {				
		'title': 'Vacío (Invasión)',
		'detalhenormal': 'El jefe no tiene mecánicas complicadas. Se recomienda atacar por la espalda para causar más daño.',
		'detalheheroico': 'El jefe no tiene mecánicas complicadas. Se recomienda atacar por la espalda para causar más daño.<br/>Ahora el jefe tiene una cuarta fase, lo que lo hace más desafiante.',
		'titulomissao':'Comienzo del Caos',
		'itemtitulovazioinvasao_nomedoitem':'Comienzo del Caos',
		'itemtitulovazioinvasao_tipo':'Título',
		'itemtitulovazioinvasao_custo':'Cristal 0',		
		'itemtitulovazioinvasao_efeito1':'Ataque Especial +5000',
		'itemtitulovazioinvasao_efeito2':'Defensa Especial +5000',
		'itemtitulovazioinvasao_efeito3':'Daño Crítico +178.80%',
		'itemtitulovazioinvasao_efeito4':'Lanza Infernal +5000',
		'itemtitulovazioinvasao_efeito5':'Resistencia a la Corrupción +125',
		'itemtitulovazioinvasao_efeito6':'Resistencia Especial +30.00%'
	}
};

const TraducaoIndex = {
	'en': {				
		'wiki': 'WIKI',
		'loja':'Shop',
		'guiamissoes': 'Progression Guides',
		'altar':'Altar of Invocation',
		'refugio':'Forsaken Spirit Asylum',
		'berco':'Cradle of Scarlet Flames',
		'blitzchen':'Blitzchen Lair',
		'hades':"Hades' Hell",
		'henir':"Henir's Time and Space",
		'reigosma':'King Slime',
		'santuario':'Frozen Sanctuary',
		'md':'Dimensional Curse',
		'vazioinvasao':'Void (Invasion)',		
		'cripta':'Ancestral Crypt',
		'sacrario':'Spirit Sanctum'
	},
	'pt': {				
		'guiamissoes': 'Guias de Progressão',
		'loja':'Loja',
		'altar':'Altar da Invocação',
		'refugio':'Refúgio Devastado dos Espíritos',
		'berco':'Berço das Chamas Escarlates',
		'blitzchen':'Covil de Blitzchen',
		'hades':"Domínio de Hades",
		'henir':"Tempo e Espaço de Henir",
		'reigosma':'Rei Gosma',
		'santuario':'Santuário Esquecido',
		'md':'Maldição Dimensional',
		'vazioinvasao':'Vazio (Invasão)',
		'cripta':'Cripta Ancestral',		
		'sacrario':'Sacrário dos Espíritos'
	},
	'es': {				
		'guiamissoes': 'Guías de Progresión',
		'loja':'Tienda',
		'altar':'Altar de Invocación',
		'refugio':'Refugio Devastado de los Espíritus',
		'berco':'Cuna de las Llamas Escarlatas',
		'blitzchen':'Guarida de Blitzchen',
		'hades':"Infierno de Hades",
		'henir':"Tiempo y Espacio de Henir",
		'reigosma':'Rey Baba',
		'santuario':'Santuario Olvidado',
		'md':'Maldición Dimensional',
		'vazioinvasao':'Vacío (Invasión)',
		'cripta':'Cripta Ancestral',
		'sacrario':'Sanctum de los Espíritus'
	},
	'ph': {				
		'guiamissoes': 'Mga Gabay sa Pag-unlad',
		'loja':'Tindahan',
		'altar':'Altar ng Panawagan',
		'refugio':'Sinumpang Kanlungan ng mga Espiritu',
		'berco':'Duyan ng mga Alab na Pulang-pula',
		'blitzchen':'Lungga ng Blitzchen',
		'hades':"Impiyerno ni Hades",
		'henir':"Oras at Espasyo ni Henir",
		'reigosma':'Hari ng Putik',
		'santuario':'Nakalimutang Santuwaryo',
		'md':'Dimensiyonal na Sumpa',
		'vazioinvasao':'Kawalan (Pagsalakay)',
		'cripta':'Sinaunang Libingan',
		'sacrario':'Santuwaryo ng mga Espiritu'
	},
	'cn': {				
		'guiamissoes': '进度指南',
		'loja':'店铺',
		'altar':'召唤祭坛',
		'refugio':'遗弃之灵的避难所',
		'berco':'猩红火焰之摇篮',
		'blitzchen':'Blitzchen 巢穴',
		'hades':"哈迪斯的地狱",
		'henir':"赫尼尔的时空",
		'reigosma':'史莱姆王',
		'santuario':'冰冻圣地',
		'md':'次元诅咒',
		'vazioinvasao':'虚空（入侵）',
		'cripta':'祖先墓穴',
		'sacrario':'灵魂圣殿'
	},
	'id': {				
		'guiamissoes': 'Panduan Perkembangan',
		'loja':'Toko',
		'altar':'Altar Pemanggilan',
		'refugio':'Suaka Roh yang Ditinggalkan',
		'berco':'Buaian Api Merah Scarlet',
		'blitzchen':'Sarang Blitzchen',
		'hades':"Neraka Hades",
		'henir':"Ruang dan Waktu Henir",
		'reigosma':'Raja Lendir',
		'santuario':'Sangtuari Beku',
		'md':'Kutukan Dimensional',
		'vazioinvasao':'Kekosongan (Invasi)',
		'cripta':'Kubah Leluhur',
		'sacrario':'Sanctum Roh'
	},
	'th': {				
		'guiamissoes': 'คู่มือการพัฒนา',
		'loja':'ร้านค้าเล็กๆ',
		'altar':'แท่นบูชาสำหรับการอัญเชิญ',
		'refugio':'ที่ลี้ภัยของวิญญาณที่ถูกทอดทิ้ง',
		'berco':'เปลของเปลวไฟสีแดงเพลิง',
		'blitzchen':'รังของบลิทเซน',
		'hades':"นรกของฮาเดส",
		'henir':"ห้วงกาลของเฮนเนียร์",
		'reigosma':'ราชาสไลม์',
		'santuario':'ศาลเจ้าที่ถูกลืม',
		'md':'คำสาปมิติ',
		'vazioinvasao':'ความว่างเปล่า (การบุกรุก)',
		'cripta':'ห้องใต้ดินบรรพบุรุษ',
		'sacrario':'สถานศักดิ์สิทธิ์แห่งวิญญาณ'
	}
};